# SEE: https://github.com/remiprev/teamocil
name: code_fund_ads
windows:
  - name: vim
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.6
        - asdf local nodejs 13.11.0
        - nvim
        focus: true

  - name: console
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.6
        - asdf local nodejs 13.11.0
        - bundle exec rails c

  - name: rails
    root: /path/to/project
    layout: even-horizontal
    panes:
      - commands:
        - asdf local ruby 2.6.6
        - asdf local nodejs 13.11.0
        - lsof -t -i tcp:3000 | xargs kill -KILL
        - redis-cli flushall
        - bundle exec rails s
      - commands:
        - asdf local ruby 2.6.6
        - asdf local nodejs 13.11.0
        - lsof -t -i tcp:3035 | xargs kill -KILL
        - bundle exec ./bin/webpack-dev-server

  - name: workers
    root: /path/to/project
    layout: main-vertical
    panes:
      - commands:
        - asdf local ruby 2.6.6
        - asdf local nodejs 13.11.0
        - redis-cli flushall
        - bundle exec sidekiq -C config/sidekiq.yml
